# Install Tmux Plugin Manager first:
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

set-option -sa terminal-overrides ",xterm:Tc"
set -g mouse on

#====================================================================================
# Start numbering with 1
#====================================================================================
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-window-option 
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'
#====================================================================================
# Change super combination
#====================================================================================
# unbind C-b
# set -g prefix C-Space
# bind C-Space send-prefix

#====================================================================================
# Set status
#====================================================================================
set -g status-justify left
set -g status-left-length 200
set -g status-right-length 200
set -g status-position top
set -g status-style 'bg=#1e1e2e' #transparent
#====================================================================================
# List of plugins
#====================================================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'

#====================================================================================
# copy-paste in vi style
#====================================================================================
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# import
if-shell "uname -s | grep -q Darwin" "source ~/.config/tmux/macos.conf"

source ~/.config/tmux/utility.conf
